---
- name: Install Python 3 pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Python PyMySQL module
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: true
