---
- name: Install OS-specific dependencies
  ansible.builtin.include_tasks: "install-dependencies-{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific configuration tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family | lower }}.yml"

- name: Include MySQL secure installation tasks
  ansible.builtin.include_tasks: "secure-installation.yml"

- name: Include MySQL databases creation tasks
  ansible.builtin.include_tasks: "create-databases.yml"

- name: Include MySQL users creation tasks
  ansible.builtin.include_tasks: "create-users.yml"
