---
- name: Copy .my.cnf file to the host
  ansible.builtin.template:
    src: templates/.my.cnf.j2
    dest: "/root/.my.cnf"
    owner: root
    group: root

- name: Set the root password
  community.mysql.mysql_user:
    login_user: ""
    login_password: ""
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  no_log: true

- name: Disallow root login remotely
  ansible.builtin.command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE USER='root' AND HOST NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Delete anonymous MySQL server user
  community.mysql.mysql_user:
    user: ""
    state: absent

- name: Removes the MySQL test database
  community.mysql.mysql_db:
    db: test
    state: absent
